# example_values.yml, based on what is deployed on the APA dev kubernetes
appConfig:
  dbHost: quoteserver-db-postgresql
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  className: private
  enabled: true
  tls:
    - hosts:
        - quoteserver.sanbi.ac.za
      secretName: quoteserver-tls
  hosts:
    - host: quoteserver.sanbi.ac.za
      paths:
        - path: /
          pathType: ImplementationSpecific

