# example_values.yml, based on what is deployed on the APA dev kubernetes
appConfig:
  dbHost: projects-svc-db-postgresql
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  className: private
  enabled: true
  tls:
    - hosts:
        - apaprojects-svc.sanbi.ac.za
      secretName: projects-svc-tls
  hosts:
    - host: apaprojects-svc.sanbi.ac.za
      paths:
        - path: /
          pathType: ImplementationSpecific


container:
  port: 5000

extraEnv:
  - PROJECTS_SVC_SECRET: someSecret
  # - CORS_ORIGINS: "*"

probes:
  liveness:
    path: /swagger
  readiness:
    path: /swagger

